### ISSUE TITLE
Rails 5.2 compatibility

### ISSUE THREAD

**Issue by dtelaroli** [patricklindsay/wice_grid#11]

**Comment by dtelaroli** [comment]
Is the project closed for improvements?

I have tried upgrade my project but I couldn't because the gem fixes the Rails version from 5.0 to 5.1
s.add_dependency 'rails', '~> 5.0', '< 5.2'

**Comment by patricklindsay** [comment]
I'm currently not able to test on Rails 5.2 but if someone wants to do that & then submit a PR they are more than welcome.
