### ISSUE TITLE
Test on all minor Rails versions supported

### ISSUE THREAD

**Issue by JasonBarnabe** [patricklindsay/wice_grid#21]
Modify the test suite to run on Rails 5.0, 5.1, and eventually 5.2. Use https://github.com/thoughtbot/appraisal ?

**Comment by patricklindsay** [comment]
Sounds good. Although the current test suite is taking way to long as it is. 

I think we should concentrate on improving the test suite time. Seems like most of the time is spent on creating massive amounts of fixtures. Are these even needed? The debug logging doesn't help either.
