### ISSUE TITLE
wice_grid: undefined method `tag_options' error in Rails 6

### ISSUE THREAD

**Issue by tenzan** [patricklindsay/wice_grid#72]
I have installed the gem following its instructions
https://github.com/patricklindsay/wice_grid

#Environment

 - Ubuntu 18.04 
 - ruby 2.6.5p114
 - Rails 6.0.2.1

#application.js

    require("@rails/ujs").start()
    require("turbolinks").start()
    require("@rails/activestorage").start()
    require("channels")
    require("jquery")
    require("jquery_ujs")
    require("jquery-ui")
    require("wice_grid")
    require("bootstrap-datepicker")
    
    import "bootstrap";
    import "../stylesheets/application";
    
    document.addEventListener("turbolinks:load", () => {
        $('[data-toggle="tooltip"]').tooltip()
        $('[data-toggle="tooltip"]').popover()
    })

#application.scss

    @import "../node_modules/bootstrap/scss/bootstrap";
    @import "wice_grid";
    @import "font-awesome-sprockets";
    @import "font-awesome";

#webpack/environment.js

    const { environment } = require("@rails/webpacker");
    const webpack = require("webpack");
    
    environment.plugins.append(
      "Provide",
      new webpack.ProvidePlugin({
        $: "jquery",
        jQuery: "jquery",
        Popper: ["popper.js", "default"]
      })
    );
    
    module.exports = environment;

#customers_controller.rb

      def index
        @customers_grid = initialize_grid(Customer)
      end

#views/customers/index.html

    <%= grid(@customers_grid) do |g|
    
      g.column do |customer|
        customer.id
      end
    
    end -%>

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/zGCdu.png

**Comment by kreintjes** [comment]
Hi @tenzan, which version/branch/fork of this gem are you using? The current version (4.1.0) is not Rails 6 compatible according to the gemspec (https://github.com/patricklindsay/wice_grid/blob/v4.1.0/wice_grid.gemspec#L18).

I have a fork of this gem with Rails 6 support and some other fixes, see https://github.com/kreintjes/wice_grid/tree/fix/all which you can install with `gem 'wice_grid', '~> 4.1', github: 'kreintjes/wice_grid', branch: 'fix/all'` in your Gemfile. It is currently working for me in a project running Rails 6.0.2.1/Ruby 2.6.5 with various grids.

**Comment by tenzan** [comment]
Hi @kreintjes 
I think I was trying the version `3.6.0.pre4`.

**Comment by kreintjes** [comment]
@tenzan A well that version is a bit outdated. If you are still running into this problem, could you then try version 4.1.0 or even better my fork (`gem 'wice_grid', '~> 4.1', github: 'kreintjes/wice_grid', branch: 'fix/all'`) and let me know the results? Otherwise please close this issue.

**Comment by tenzan** [comment]
@kreintjes Thanks a lot! I will try next chance.
