### ISSUE TITLE
Update kaminari dependency

### ISSUE THREAD

**Issue by ccatterina** [patricklindsay/wice_grid#78]
Hi,
Kaminari v1.2.1, released last week, fixes a security issue ([changelog](https://github.com/kaminari/kaminari/blob/master/CHANGELOG.md)) but I can't update it because wice_grid requires version ~> 1.1.0. Are you planning to update this dependency?
Thanks

**Comment by kreintjes** [comment]
The lock on Kaminari has been loosened, so this gem won't block an update of Kaminari to v1.2.1 any longer: https://github.com/patricklindsay/wice_grid/pull/80.

This commit is currently in master and can be used by directly using the master branch of this fork: `gem 'wice_grid', '~> 4.1', github: 'patricklindsay/wice_grid'`.

Unfortunately I do not have the access to publish a new RubyGems version of this gem. Maybe @patricklindsay or @leikind can do that. Or give me access to do it.
