### ISSUE TITLE
Implement CI w/ GitHub

### ISSUE THREAD

**Issue by patricklindsay** [patricklindsay/wice_grid#8]
This task is part of the [Setup CI Build](https://github.com/leikind/wice_grid_testbed) project.

Prerequsites to this task are #6 & #7  

Task involves;
1. Setup CI build to run on all commits & PRs - Possibly using CircleCi
2. Link results to GitHub 

I'll start this task once #6 & #7 are complete.

**Comment by JasonBarnabe** [comment]
1. Sign up for https://travis-ci.org/ (free for open source)
2. `appraisal generate --travis`
3. Done?
